### PR TITLE
Add `-check` flag to check if local CA is installed or not

### PR DESCRIPTION
**Pull request by ruudk**
When using `mkcert` as part of an automation script you sometimes want to know if the user already installed the local CA or not.

Running `mkcert -install` out of the blue could confuse users because they don't know what's happening.

Therefore, it's better to first check if the local CA is installed with `mkcert -check`. If that returns a zero exit code, all is good. If it returns a non-zero exit code, it means that the local CA is not installed and the user can be instructed on what to do next (`mkcert -install`).

## How does it look?

```
$ mkcert -check
Note: the local CA is not installed in the system trust store.
Note: the local CA is not installed in the Firefox trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️

$ echo $?
1

$ mkcert -install
The local CA is now installed in the system trust store! ⚡️
The local CA is now installed in the Firefox trust store (requires browser restart)! 🦊

$ mkcert -check
All good!

$ echo $?
0
```

### CODE REVIEW

**Comment by ruudk** [comment]
@FiloSottile I ❤️  this project and you're probably busy, but is there anything I can add or change to get this merged? 🙏

**Comment by gaby** [comment]
@FiloSottile any chance you can merge this?

**Comment by ruudk** [comment]
@FiloSottile I rebased the PR. Could you please approve the workflow so that we can see if it passes? It would be so good to have this check in there, as it makes automation much easier. Thanks 🙏

**Comment by gaby** [comment]
Looking forward to this getting merged

**Comment by oyed** [comment]
Would also love to have this merged for automation purposes.

**Comment by adriangb** [comment]
+1 for this

**Comment by crazyx13th** [comment]
my current workaround
- generate a fake cert
- (add to gitignore)
- parsing output 'Note: the local CA is not installed in the system trust store.'
- delete these two files
```
`${mkcertPath} -key-file src/tools/helper/mkcert/detect-ca-is-installed.key -cert-file src/tools/helper/mkcert/detect-ca-is-installed.pem detect-ca-is-installed`
```

**Pull request closed without merging**
