### PR TITLE
Added guide for converting mkcert .pem certificates to IIS .pfx certificates

### PR DESCRIPTION
**Pull request by aweber1**
I wasn't sure where to put the guide, so just created a separate file for it with a link from the main readme.

### CODE REVIEW

**Comment by aweber1** [comment]
oh nice! I didn't see that `-pkcs12` option 😄 

I can confirm that `mkcert -pkcs12 localdomain.net` generates a `.p12` file that can be renamed to `.pfx` and imported into IIS using the default `changeit` password.

Very cool! And totally negates the need for this doc 😉

Do you mind if I change this PR to add the above process for creating IIS pfx to the readme?

**Comment by aweber1** [comment]
Cool. I'm writing a medium post right now 😄 

As for the password, probably not terribly useful, it's just required when generating the PKCS cert and when importing it into IIS. As long as it's obvious that `changeit` is the default and that you shouldn't be sharing the cert I think leaving it as-is is probably ok?

**Comment by FiloSottile** [comment]
Cool, I’d be inclined to make it configurable if there was some software that requires a different password, but otherwise I don’t want anyone relying on the terrible encryption that PKCS#11 provides.

Thanks again!

**Comment by aweber1** [comment]
Adding here for reach: https://medium.com/@aweber01/locally-trusted-development-certificates-with-mkcert-and-iis-e09410d92031

**Pull request closed without merging**
