### PR TITLE
Add Linux support for update-ca-trust and update-ca-certificates (RHEL, CentOS, Fedora, Debian, Ubuntu...)

### PR DESCRIPTION
**Pull request by chlunde**
Hmm, are there any better tools than "tee" to install files using sudo? :)

### CODE REVIEW

**Comment by chlunde** [comment]
Dropping this as per-user setup has been implemented

**Comment by FiloSottile** [comment]
Hey, I'd still like to merge this as part of the Linux support. The current code only supports Firefox, but I want it to also work with system stores. Is that ok?

**Comment by adamdecaf** [comment]
> I want it to also work with system stores. Is that ok?

Same. I can help get debian flavors working.

**Comment by chlunde** [comment]
Sure, no problem.  I updated with Debian support too, tested briefly on raspbian, but I'm not sure how you would like this to work.  Should it be behind a flag?

PS!  The package with certutil is called nss-tools on Fedora

**Comment by adamdecaf** [comment]
What would the flag be? Why?

**Comment by FiloSottile** [comment]
Thank you!

**Pull request merged**
