### PR TITLE
Add Firefox Flatpak support

### LINKED ISSUE #409: Support Firefox in Flatpak (if possible)
In a similar way to #325, it would be nice if this could work with [Firefox that is running in a Flatpak](https://flathub.org/apps/details/org.mozilla.firefox), if at all possible.

### PR DESCRIPTION
**Pull request by noverby**
Fixes  #409

### CODE REVIEW

**Comment by compiaffe** [comment]
Very nice!  @filippobuletto can we get this merged, please?

**Comment by filippobuletto** [comment]
Surely you mean @FiloSottile :)

**Comment by compiaffe** [comment]
Haha, yes I absolutely mean @FiloSottile :)

**Comment by compiaffe** [comment]
@FiloSottile friendly ping :)

**Comment by francoism90** [comment]
I think the project is dead. :/

**Comment by bugnano** [comment]
@FiloSottile friendly ping :)

**Comment by lossendae** [comment]
@FiloSottile friendly ping :)

**Comment by noverby** [comment]
The project seems to be dead, so I'm closing this.

**Comment by bugnano** [comment]
@noverby I wouldn't have closed this issue.

Yes, this project *looks* abandoned, and I also asked if it was on #548 .
According to @gaby the maintainer of this project, every now and then remembers that this project exists.

By closing this issue, you only prevent this PR from ever getting merged.

What was the problem of keeping this PR open?

**Comment by rfay** [comment]
Yes, it seems like he stops by about every 2 years :)

**Comment by noverby** [comment]
@bugnano I thought that there was no chance of this being merged,
but you convinced me otherwise, so I will open it again.

**Comment by overby-me** [comment]
I have switched to [rcgen](https://github.com/rustls/rcgen), so I'll close this PR. Feel free to open a new PR with my changes.

**Comment by francoism90** [comment]
@noverby How does rcgen work? It seems to be a rust lib, instead of an actually complete solution like `mkcert`.

**Review by 818Nawaf — COMMENTED** [review]
اوافق

**Review by 818Nawaf — COMMENTED** [review]
موافق

**Comment by DavidPetrasek** [comment]
Temporary solution until this is merged:
1. Open Flatpak Firefox and go to:
2. Preferences → Privacy & Security → Certificates → View Certificates → Authorities → Import…
3. Navigate to ~/.local/share/mkcert/rootCA.pem, select it, and trust it for identifying websites.

**Comment by overby-me** [comment]
@francoism90 I have created a Nix package that builds the rustls-cert-gen binary from rcgen:

https://github.com/noverby/noverby/blob/main/packages/rcgen.nix

**Pull request closed without merging**
