### PR TITLE
Adding guide for installing mkcert on archlinux

### PR DESCRIPTION
**Pull request by unixfox**
I created an AUR PKGBUILD to quickly install mkcert on ArchLinux: https://aur.archlinux.org/packages/mkcert-git/.

### CODE REVIEW

**Comment by FiloSottile** [comment]
Thank you! Can I ask why the `-git` suffix?

Also, should I ping you when I make a v1 release?

**Comment by kervich** [comment]
`-git` is simply an Arch User Repo package naming convention (meaning tha package originates from a working/master branch of an open-source project's git repo).

**Comment by FiloSottile** [comment]
Makes sense, I was asking because I have now tagged v1, so maybe it's appropriate to make a PKGBUILD targeting that instead of master?

**Comment by unixfox** [comment]
I could do both. It's common to have the git pkgbuild and the stable version pkgbuild.

**Pull request merged**
