### PR TITLE
Support SLES & OpenSUSE

### PR DESCRIPTION
**Pull request by ricardobranco777**
Add support for SLES & OpenSUSE.

### CODE REVIEW

**Comment by adamdecaf** [comment]
👍but I don't have those systems to test. Have you confirmed this?

**Comment by ricardobranco777** [comment]
> but I don't have those systems to test. Have you confirmed this?

I developed the PR on OpenSUSE Tumbleweed and tested it on SLES 12 & 15.  SUSE imported the `update-ca-certificates` utility from Debian but changed the directories.

**Comment by ricardobranco777** [comment]
> but I don't have those systems to test. Have you confirmed this?

You can use the `opensuse:leap` or `opensuse:tumbleweed` Docker images.

**Comment by adamdecaf** [comment]
Sounds good. Only @FiloSottile can merge PR's

**Comment by FiloSottile** [comment]
Thank you!

**Pull request merged**
