### PR TITLE
Adds support to pass CA name

### PR DESCRIPTION
**Pull request by yasirmturk**

### CODE REVIEW

**Comment by gabrielcalderon** [comment]
@yasirmturk Your changes are using a variable out of scope. The name of these files are global variables.

**Comment by FiloSottile** [comment]
Thank you, but generally the user does not interact with the root CA files, so I don't think we need to make them customizable.

**Comment by eleven-net-cn** [comment]
> Thank you, but generally the user does not interact with the root CA files, so I don't think we need to make them customizable.

When we want to generate a certificate used by the team, and used in multiple projects, it is better to allow the rootCA name to be specified, suggest to reconsider this proposal.

**Comment by yasirmturk** [comment]
people are doing it and want to do it, means it is part of the req.

**Pull request closed without merging**
